export default{
  login: "Vik0411",
  id: 50553439,
  node_id: "MDQ6VXNlcjUwNTUzNDM5",
  avatar_url: "https://avatars.githubusercontent.com/u/50553439?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Vik0411",
  html_url: "https://github.com/Vik0411",
  followers_url: "https://api.github.com/users/Vik0411/followers",
  following_url: "https://api.github.com/users/Vik0411/following{/other_user}",
  gists_url: "https://api.github.com/users/Vik0411/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Vik0411/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Vik0411/subscriptions",
  organizations_url: "https://api.github.com/users/Vik0411/orgs",
  repos_url: "https://api.github.com/users/Vik0411/repos",
  events_url: "https://api.github.com/users/Vik0411/events{/privacy}",
  received_events_url: "https://api.github.com/users/Vik0411/received_events",
  type: "User",
  site_admin: false,
  name: "Vik0411",
  company: "Erste Group IT",
  blog: "viktorsvoboda.blogspot.com/",
  location: "Praha",
  email: null,
  hireable: null,
  bio: 'developing developer',
  twitter_username: "svoboda411",
  public_repos: 10,
  public_gists: "xy",
  followers: "xy",
  following: "xy",
  created_at: "2019-05-12T17:22:27Z",
  updated_at: "2022-04-21T16:08:27Z"
}